-- Aggregates and Grouping

-- (1) How many films are available in each rating category?
select * from sakila.film; -- printing the database
select count(*), rating 
from sakila.film
group by rating;

-- (2) Find the total revenue generated by each store.
select * from sakila.customer; -- cust id, store id
select * from sakila.film; -- film id, rental rate, rental duration, replacement cost
select * from sakila.inventory; -- inv id, film id, store id
select * from sakila.payment; -- cust id, rental id, staff id, rental id, amount
select * from sakila.rental; -- rental id, inv id, cust id, staff id. 
select * from sakila.store; -- store id, manager_staff_id
select * from sakila.staff; -- staff id
select store_id, sum(amount) as total_revenue
from sakila.payment
join sakila.rental 
on sakila.rental.rental_id = sakila.payment.rental_id
join sakila.store
on sakila.store.manager_staff_id = sakila.rental.staff_id
group by store_id;


-- (3) Count the number of rentals made per customer.
select * from sakila.rental; -- rental id, cust id
select * from sakila.customer; -- cust id
select sakila.customer.customer_id, count(rental_id) as total_rentals
from sakila.rental
join sakila.customer 
on sakila.customer.customer_id = sakila.rental.customer_id
group by sakila.customer.customer_id;

