USE SAKILA;
-- 1. Find the total number of films in the database.
select count(*) as totalfilms from film;

-- 2. Find the average rental rate across all films.
select avg(rental_rate) as avgrentalrate from film;

-- 3. Find the shortest and longest film length in the database.
select min(length), max(length) from film;

-- 4. Find the total number of customers per store.
select store_id, count(customer_id) as total_customers from customer
group by store_id;

-- 5. Find the total revenue (sum of payment amount) generated by each store (hint: you'll need to join payment → staff → store, since payment doesn't directly have store_id).
select store_id, sum(amount) as total_revenue from payment
join staff using (staff_id)
join store using (store_id)
group by store_id;

-- 6. Find the number of films in each category, sorted by count descending.
select category_id, name as category_name, count(film_id) as total_films from film
join film_category using (film_id)
join category using (category_id)
group by category_id
order by total_films desc;

-- 7. Find the average rental rate per category, sorted by average descending.
select category_id, name as category_name, avg(rental_rate) as avg_rental_rate from film
join film_category using (film_id)
join category using (category_id)
group by category_id
order by avg_rental_rate desc;

-- 8. Find categories that have more than 60 films (use HAVING).
select category_id, count(film_id) as total_films from film_category
group by category_id
having total_films >60;

-- 9. Find customers who have made more than 40 payments total.
select customer_id, count(payment_id) as total_payments from payment
group by customer_id
having total_payments>40;

-- 10. Find the total amount paid, grouped by customer, but only show customers whose total payments exceed 150.
select customer_id, sum(amount) as total_amount from payment
group by customer_id
having total_amount>150;

-- 11. Find the top 5 customers by total amount spent, showing their name and total.
select customer_id, first_name, last_name, sum(amount) as total_amount from customer
join payment using (customer_id)
group by customer_id
order by total_amount desc
limit 5;


-- 12. Find actors who have appeared in more than 25 films, showing actor name and film count, sorted by count descending.
select actor_id, concat(first_name, ' ', last_name) as actor_name, count(film_id) as total_films from film
join film_actor using (film_id)
join actor using (actor_id)
group by actor_id
having total_films>25
order by total_films desc;